// <auto-generated />
using System;
using Assignment_3_EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_3_EFCore.Migrations
{
    [DbContext(typeof(AirLineDBContext))]
    partial class AirLineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Al_Id")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("aircraftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("aircraftId");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Aircraft_Routes", b =>
                {
                    b.Property<int>("AC_Id")
                        .HasColumnType("int");

                    b.Property<int>("Route_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Of_Pass")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AC_Id", "Route_Id", "Departure");

                    b.HasIndex("Route_Id");

                    b.ToTable("aircraft_Routes");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cont_Person")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Airline_Phones", b =>
                {
                    b.Property<int>("Al_Id")
                        .HasColumnType("int");

                    b.Property<int>("Phones")
                        .HasColumnType("int");

                    b.HasKey("Al_Id", "Phones");

                    b.ToTable("airline_Phones");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Emp_Qualifications", b =>
                {
                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Emp_Id", "Qualifications");

                    b.ToTable("emp_Qualifications");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Al_Id")
                        .HasColumnType("int");

                    b.Property<string>("BD_Day")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BD_Month")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BD_Year")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Al_Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Al_Id")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Al_Id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Aircraft", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Airline", "aircraft")
                        .WithMany("aircraft")
                        .HasForeignKey("aircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Assignment_3_EFCore.AirlinesModels.Crew", "crew", b1 =>
                        {
                            b1.Property<int>("AircraftId")
                                .HasColumnType("int");

                            b1.Property<string>("Assistant")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("Host1")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("Host2")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<int>("Maj_Pilot")
                                .HasColumnType("int");

                            b1.HasKey("AircraftId");

                            b1.ToTable("Aircraft");

                            b1.WithOwner()
                                .HasForeignKey("AircraftId");
                        });

                    b.Navigation("aircraft");

                    b.Navigation("crew")
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Aircraft_Routes", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Aircraft", "aircraft")
                        .WithMany("aircraft_Routes")
                        .HasForeignKey("AC_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Route", "routes")
                        .WithMany("aircraft_Routes")
                        .HasForeignKey("Route_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aircraft");

                    b.Navigation("routes");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Airline_Phones", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Airline", "airline")
                        .WithMany("airline_Phones")
                        .HasForeignKey("Al_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airline");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Emp_Qualifications", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Employee", "employee")
                        .WithMany("emp_Qualifications")
                        .HasForeignKey("Emp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Employee", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Airline", "airline")
                        .WithMany("employee")
                        .HasForeignKey("Al_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airline");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Transaction", b =>
                {
                    b.HasOne("Assignment_1_EFCore.AirlinesModels.Airline", "airlines")
                        .WithMany("transaction")
                        .HasForeignKey("Al_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airlines");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Aircraft", b =>
                {
                    b.Navigation("aircraft_Routes");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Airline", b =>
                {
                    b.Navigation("aircraft");

                    b.Navigation("airline_Phones");

                    b.Navigation("employee");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Employee", b =>
                {
                    b.Navigation("emp_Qualifications");
                });

            modelBuilder.Entity("Assignment_1_EFCore.AirlinesModels.Route", b =>
                {
                    b.Navigation("aircraft_Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
